// Owner: lead (Phase 2b: frozen after F0; changes go through the lead. Never rename or remove a key).
// GameConfig: every tunable (02 §3 plus values referenced in 02/03/04/05). Single source of truth.
// This module is a LEAF: it imports nothing, so every layer (engine scripts, game, platform, ui, app)
// may import it. Functions that depend on config should take `c: GameConfig = cfg` so tests can
// pass a variant built with mergeConfig().

// Phase 2b (docs/phase2b/parity-spec.md §10): F0 added every new key below with the spec's values.
// After F0 this file is frozen for workstreams A–E: value changes go through the lead.
// Phase 2c (docs/phase2c/fish-lives-spec.md §8): the spec stage added the 2c keys (levelPoints,
// period, rank.boards.period, rank.dailyBoard, rank.periodEpoch, groups.placeHints, iap.catalog,
// iap.retired, fx.lifeLoss*, fx.win.panelAfterLastMs / scrimLeadMs) and marked the keys 2c stops
// reading @deprecated (the fish wallet and swaps, paw points, the heart break). Workstreams G1–G3
// do not edit this file; value changes go through the lead.
// Phase 2c.1 (fish-lives-spec §3.1–§3.2, §10; user, first-hand, 2026-10-10): level points are
// earned PER CAT inside one level (levelPoints.firstIncrement, levelPoints.step) and shown by a HUD
// counter (fx.levelPoints). The per-win formula and the cross-level perfect streak are gone: their
// keys (levelPoints.perSize, hardMultiplier, streakStep, streakCap) are @deprecated and unread.
// Phase 2d (docs/phase2d/look-spec.md §1, §4; user decision 2026-10-10: match the original's game
// screen look and layout from the user's own recording): the spec stage added layout.game (the
// scaled vertical stack measured at 402 CSS px), layout.mark (the X glyph), fx.helperPulse,
// fx.headFoundMs, fx.markPopMs, fx.mouseStaggerMs, fx.startToast, mouse (the third helper),
// settingsDot, ads.banner.duringPlay / bannerPx, and widened RewardedPlacementId (+ 'mouse') and
// BannerScreen (+ 'game'). The game-screen keys they replace are @deprecated (unread once 2d is
// built). No existing value changed except the unread ads.rewarded.placements list (+ 'mouse').
// Phase 2d.1 (docs/phase2d/helpers-spec.md §0.6; user decision D-2d1-0, 2026-10-10: replicate the
// original's three helpers, the level-start tickers and the palette from the user's own recordings):
// L0 added fx.helperPulse.idleMs / needsStock / untilHelperUsed ('auto' changes meaning, §4.6) and
// the groups fx.markDraw, fx.mouse, fx.catPlaced, fx.points, fx.unitDone, fx.hint, fx.tickers,
// layout.hint and the key ads.banner.hideDuringHint, and changed three values: fx.headFoundMs
// 300 → 280, fx.markPopMs 140 → 170 (the mouse's X only) and kitty.revealMs 600 → 820. Marked
// @deprecated phase2d.1: fx.mouseStaggerMs and fx.startToast (unread once 2d.1 is built), and
// fx.levelPoints.rollMs / plusMs / plusRisePx (no longer read by the Score column). Workstreams
// G1–G3 do not edit this file; value changes go through the lead.

/** The 17 locales of phase2b §6.2 (BCP 47 ids; FB `ll_CC` codes are mapped onto them by i18n/locale.ts, §6.3). */
export type LocaleId =
  | 'en' | 'es' | 'pt-BR' | 'fr' | 'de' | 'it' | 'id' | 'tr' | 'pl'
  | 'ru' | 'vi' | 'th' | 'ja' | 'ko' | 'zh-Hans' | 'hi' | 'ar';
/**
 * FB in-app product ids (phase2b §8.3): our own, lowercase. Prices live in the FB dashboard.
 * Phase 2c §5.3: `fish_250` and `fish_900` are RETIRED (never sold again; listed in iap.retired so a
 * ledger entry or an unconsumed purchase of them stays valid and is compensated in hints and kitties).
 */
export type ProductId = 'remove_ads' | 'hints_15' | 'kitties_8' | 'fish_250' | 'fish_900';
/** Phase 2c §4.1: the leaderboard period, in UTC calendar units (weeks start Monday 00:00 UTC). */
export type PeriodKind = 'day' | 'week' | 'month';
/** Phase 2c §3, §4: the modes whose counted wins can earn level points and leaderboard points. */
export type ScoredMode = 'level' | 'daily' | 'event';
/** Interstitial triggers (02 §13.2 + phase2b §3.2 `event_next`). Mirrors platform InterstitialPlacement. */
export type InterstitialTrigger = 'next_level' | 'retry' | 'daily_done' | 'event_next';
/**
 * Rewarded placements (02 §13.3 + phase2b §5.6 `group_double`). Mirrors platform RewardedPlacement.
 * Phase 2d (look-spec §1.12): + 'mouse', the third helper (one rewarded video per use).
 */
export type RewardedPlacementId = 'hint' | 'kitty' | 'revive' | 'group_double' | 'mouse';
/**
 * Screens that may carry an FB banner (phase2b §3.2). Phase 2d (look-spec §1.16): + 'game', the
 * game screen during play, only while ads.banner.duringPlay is on (it is not in ads.banner.screens).
 */
export type BannerScreen = 'home' | 'victory' | 'event' | 'game';
/**
 * Phase 2d (look-spec §1.11): which helper the idle pulse invites. 'auto': the kitty while nothing is
 * marked or placed in the attempt, then the bulb (fits both observations of the user's recording).
 * Phase 2d.1 (helpers-spec §4.6, D-2d1-9, replaces D-2d-11): 'auto' still suggests the kitty while
 * every tile is empty and the bulb otherwise, but the suggested helper pulses only after
 * fx.helperPulse.idleMs without a board change, only with stock (needsStock) and only while no
 * helper has been used in the attempt (untilHelperUsed).
 */
export type HelperPulseTarget = 'auto' | 'bulb' | 'kitty' | 'off';

/** One IAP catalogue row (phase2b §8.3): what a purchase of `id` grants. */
export interface IapProductDef {
  readonly id: ProductId;
  /** The No Ads entitlement (purchases.noAds, §8.4). */
  readonly noAds?: boolean;
  readonly hints?: number;
  readonly kitties?: number;
  /** @deprecated phase2c §5: fish are lives, not a currency; no product grants fish (iap.catalog, iap.retired). */
  readonly fish?: number;
}

/** Interstitial cooldown by player tenure (02 §13.2): the row with the largest fromDay ≤ tenure applies. */
export interface CooldownStep {
  readonly fromDay: number;
  readonly sec: number;
}

export interface GameConfig {
  readonly hearts: { readonly perAttempt: number };
  readonly input: {
    readonly doubleTapMs: number;
    /** dragStartPx = max(dragStartMinPx, dragStartCellFraction × cellPx) — use dragStartPx(). */
    readonly dragStartMinPx: number;
    readonly dragStartCellFraction: number;
    readonly cellLockAfterCatMs: number;
    /** Mark sound throttle while painting (02 §16, 04 §5.4). */
    readonly paintSoundThrottleMs: number;
  };
  readonly hints: { readonly startStock: number; readonly perRewardedAd: number };
  readonly kitty: {
    readonly startStock: number;
    readonly perRewardedAd: number;
    /**
     * The board stays locked this long after KITTY (then KITTY_DONE). Phase 2d.1 (helpers-spec §2.4):
     * 600 → 820, so the lock lasts while the kitty's cat celebrates (to fx.catPlaced.celebrateUntilMs).
     */
    readonly revealMs: number;
  };
  /**
   * Phase 2d (look-spec §1.12) [DECISION-PENDING-USER]: the third helper, the mouse. Each use (one
   * rewarded video on FBIG; the free fallback with its shared cooldown on the web) marks `cells`
   * random empty tiles that cannot hold a cat with an X (one research source: 3). It has no stock.
   * `enabled: false` hides the button everywhere (its slot in the tool row stays, so nothing moves).
   */
  readonly mouse: { readonly enabled: boolean; readonly cells: number };
  readonly revive: { readonly maxPerAttempt: number; readonly heartsRestored: number };
  readonly ads: {
    readonly enabled: boolean;
    readonly readyTimeoutMs: number;
    readonly showWatchdogMs: number;
    readonly interstitial: {
      readonly minCompletedLevels: number;
      readonly cooldownSec: readonly CooldownStep[];
      readonly sessionGraceSec: number;
      /** Where an interstitial may show (02 §13.2). phase2b §3.2 adds `event_next` (lead-approved widening). */
      readonly triggers: readonly InterstitialTrigger[];
    };
    readonly rewarded: {
      readonly resetsInterstitialClock: boolean;
      /** Every rewarded placement in use (phase2b §3.2, §5.6: + `group_double`). */
      readonly placements: readonly RewardedPlacementId[];
    };
    /**
     * FB banners (phase2b §3.2). `enabled` is true from 2b, but a banner still needs the capability
     * (both loadBannerAdAsync and hideBannerAdAsync) and VITE_FB_PLACEMENT_BANNER. Never during play.
     */
    readonly banner: {
      readonly enabled: boolean;
      /** Banners only once progress.completed ≥ this [DECISION: default, user may change] (§3.2). */
      readonly fromCompletedLevels: number;
      /** The only screens that may show a banner [DECISION: default, user may change] (§3.2). */
      readonly screens: readonly BannerScreen[];
      /** loadBannerAdAsync position argument (§3.2; G4 verifies the values). */
      readonly position: 'bottom';
      /** Bottom band reserved on a banner screen: the 50 px banner + 8 px (plus safeBottom), §3.2. */
      readonly reservePx: number;
      /** Skip the banner on a screen when the last load was less than this ago (Meta's limit is 45 s), §3.2. */
      readonly minReloadSec: number;
      /** Primary buttons sit at least this far above the reserved band (§2.5, §3.2). */
      readonly buttonClearancePx: number;
      /**
       * Phase 2d (look-spec §1.16) [DECISION: default, user may change]: the game screen may carry a
       * banner during play, like the original in the user's recording (Meta's guidance against it is
       * recorded there; gate G4 re-checks before production). The same gate applies (capability,
       * fromCompletedLevels, No Ads, not the tutorial). Off: the 2b rule (never during play).
       */
      readonly duringPlay: boolean;
      /** Phase 2d: the banner's own height on the game screen's band (the band adds layout.game.toolsToBanner and .bottom, scaled). */
      readonly bannerPx: number;
      /**
       * Phase 2d.1 (helpers-spec §3.2, D-2d1-13; the user's recording): the banner is hidden while the
       * hint overlay (O1) is open. After it closes the banner shows again at once when minReloadSec has
       * passed since the last load, else one timer re-shows it when that window ends (if the same game
       * screen is still up with no modal open and the board not won). The band stays reserved. Off: the
       * 2d rule (the banner stays during the hint).
       */
      readonly hideDuringHint: boolean;
    };
    readonly unsupportedFallback: { readonly cooldownSec: number };
    /** Dev/e2e mock ad overlay length (04 §6.2). */
    readonly mock: { readonly durationMs: number };
    /** FB adapter: delays before re-loading an ad instance after consecutive load failures; after the
     *  last one it waits for the next preload()/show request (05 §6.2, no tight reload loop). */
    readonly reloadDelaysMs: readonly number[];
    /**
     * FB adapter: an instance whose loadAsync() has not settled after this long is dropped and
     * counts as a failed load (reload backoff), so a load that never settles cannot block that ad
     * kind for the session (PLAT-6). Longer than readyTimeoutMs. [platform addition]
     */
    readonly loadTimeoutMs: number;
  };
  readonly daily: {
    readonly unlockAfterLevel: number;
    /** First month with a generated daily pack (03 §8.6). */
    readonly firstPackMonth: string;
  };
  readonly levels: {
    readonly shipped: number;
    readonly hardEvery: number;
    readonly hardFrom: number;
    readonly prefetchAhead: number;
    /** Levels per pack file; pack k holds levels k*packSize+1 … (k+1)*packSize (03 §9.3). */
    readonly packSize: number;
    /** Pack fetch retry delays before falling back to a substitute board (04 §8). */
    readonly fetchRetryDelaysMs: readonly number[];
    /**
     * Per-attempt cap for a pack or daily-month request: one that has not answered by then counts as
     * a failed attempt (retry, then substitute / generated daily), so it can never hang (04 §8). [app addition]
     */
    readonly fetchTimeoutMs: number;
  };
  readonly fx: {
    /**
     * Board entry cap (phase2b §2.9): START is dispatched at entryEndMs(n) =
     * boardEntryWaveStartMs + (2n−2) × stagger + boardEntryTileMs, never later than this. Was 250.
     */
    readonly boardEntryMs: number;
    /**
     * Upper bound of the per-DIAGONAL tile stagger of the entry wave (phase2b §2.9): tile (r, c)
     * starts at boardEntryWaveStartMs + (r + c) × stagger, where
     * stagger = min(boardEntryStaggerMs, boardEntryWaveBudgetMs / (2n − 2)). (Phase 2: per row, 8.)
     */
    readonly boardEntryStaggerMs: number;
    /** Board card rise + fade at entry (phase2b §2.9). */
    readonly boardEntryCardMs: number;
    readonly boardEntryRisePx: number;
    /** First tile of the diagonal wave starts this long after the entry begins (§2.9). */
    readonly boardEntryWaveStartMs: number;
    /** One tile's scale-in (0.6 → 1.04 → 1; the scales are CSS-only constants), §2.9. */
    readonly boardEntryTileMs: number;
    /** The whole wave's stagger budget, spread over the 2n − 2 diagonals (§2.9). */
    readonly boardEntryWaveBudgetMs: number;
    /** Screen transitions (phase2b §2.9, router): outgoing fade (+ scale to 0.98 into a game). */
    readonly screenOutMs: number;
    /** Incoming slide-up + fade into a game screen, after screenInDelayMs (§2.9). */
    readonly screenInMs: number;
    readonly screenInDelayMs: number;
    readonly screenSlidePx: number;
    /**
     * Incoming fade when leaving a game (game → Home, game → event), §2.9 table row 2.
     * [F0 addition: the spec gives 200 ms in prose only]
     */
    readonly screenBackInMs: number;
    /** Reduced-motion crossfade for every screen transition and the victory screen (§2.7, §2.9). */
    readonly screenReducedMs: number;
    /**
     * Heart break (phase2b §2.9): shake, crack, falling halves and shards. Replaces the 400 ms crack.
     * @deprecated phase2c §1.3: lives are fish; the fish loss uses fx.lifeLossMs.
     */
    readonly heartBreakMs: number;
    /**
     * Phase 2c §1.3: the fish-loss animation on a MISTAKE (wriggle, flip out of the slot, droplets,
     * the empty outline fading in), total length. Reduced motion: a fx.reducedMotionFadeMs swap.
     */
    readonly lifeLossMs: number;
    /** Phase 2c §1.3: the lives pill's own shake on a MISTAKE (`.pill--hurt`). */
    readonly lifeLossPillMs: number;
    /** Board-cat idle breathing (phase2b §2.9): scale 1 → 1 + catBreatheScale → 1, phase from cellNoise. */
    readonly catBreatheMs: number;
    readonly catBreatheScale: number;
    /** Board-cat ear flick: the cat-ear-flick overlay, every earFlickMinMs…earFlickMaxMs per cat (§2.9). */
    readonly earFlickMinMs: number;
    readonly earFlickMaxMs: number;
    readonly earFlickMs: number;
    /** Home mascot head tilt timer (A, mascot.ts), every Min…Max ms (phase2b §2.9). */
    readonly mascotHeadTiltMinMs: number;
    readonly mascotHeadTiltMaxMs: number;
    /** Victory screen sun rays: one full turn (phase2b §2.5); static with reduced motion. */
    readonly victoryRaysTurnMs: number;
    /** The post-win flow (phase2b §2.2, §2.3, §2.6, §2.7). t = 0 is the WON event. */
    readonly win: {
      /** Solved-board glow (§2.2): fade in, then settle to glowSettleOpacity; staggered in row order. */
      readonly glowInMs: number;
      readonly glowSettleMs: number;
      readonly glowStaggerMs: number;
      readonly glowSettleOpacity: number;
      /** `.cell__glow` size as a multiple of the slot (A styles it, §1.10). */
      readonly glowScale: number;
      /**
       * In-game fish pill fades in (centred in the pills row) at this t, showing the pre-win count.
       * Phase 2c §2.2: the same timing drives the PERIOD COUNTER pill (this period's leaderboard
       * points before the win), which takes the fish pill's place.
       */
      readonly fishPillInAtMs: number;
      readonly fishPillFadeMs: number;
      /**
       * Fish k (0..2) pops at its source cat at fishAtMs + k × fishStaggerMs (§2.2).
       * Phase 2c §2.2: fish k (0..N−1, N = lives kept) lifts off its life icon in the HUD at this t.
       */
      readonly fishAtMs: number;
      readonly fishStaggerMs: number;
      readonly fishPopMs: number;
      /** Pause between the pop and the flight. */
      readonly fishHoldMs: number;
      readonly fishFlightMs: number;
      /** Flight path (§2.3): control point lifted by fishArcLift × |ST|, spread −/0/+ fishArcSpread per fish. */
      readonly fishArcLift: number;
      readonly fishArcSpread: number;
      /** The flight path is sampled at this many WAAPI keyframes (§2.3). [F0 addition: prose value] */
      readonly fishPathSamples: number;
      readonly fishEndScale: number;
      /**
       * Fish element size: fishSizeFraction × slot, clamped to fishMinPx…fishMaxPx (§2.3).
       * @deprecated phase2c §2.3: the flying fish starts at its life icon's size, clamped to fishMinPx…fishMaxPx.
       */
      readonly fishSizeFraction: number;
      readonly fishMinPx: number;
      readonly fishMaxPx: number;
      readonly fishTrailDots: number;
      readonly fishTrailMs: number;
      /** Pill icon bump on each arrival (§2.2). */
      readonly counterBumpMs: number;
      /** "+3" label above the pill: rise and fade. */
      readonly plusLabelMs: number;
      /**
       * How far the "+N" chip rises before it fades. Phase 2c integration (lead decision, 2026-10-09;
       * STATUS-2c §6): 24 → 6. The chip sits in the 27 px between the top-bar title and the pills row
       * and is about 26 px tall, so a 24 px rise covered "Level N" at every win; 6 px still reads as a
       * rise and keeps the title legible.
       */
      readonly plusLabelRisePx: number;
      /**
       * Hard or daily bonus label "+2" (§2.8).
       * @deprecated phase2c §2.2: there are no fish bonuses; nothing reads it after 2c.
       */
      readonly bonusLabelAtMs: number;
      /**
       * Scrim before the ranking panel (§2.2).
       * @deprecated phase2c §2.2: the scrim starts fx.win.scrimLeadMs before the panel, whose time
       * scales with the number of fish kept (panelAt(N)).
       */
      readonly scrimAtMs: number;
      readonly scrimFadeMs: number;
      /**
       * Phase 2c §2.2: the ranking panel opens this long after the last fish arrives, but never later
       * than fx.winOverlayDelayMs: panelAt(N) = min(winOverlayDelayMs, arrival(N − 1) + this).
       * 1 950 keeps the 3-fish panel at 4 500 ms (2 550 + 1 950); 1 fish → 4 200, 2 → 4 350.
       */
      readonly panelAfterLastMs: number;
      /** Phase 2c §2.2: the scrim fades in this long before panelAt(N) (was the fixed scrimAtMs 4 200). */
      readonly scrimLeadMs: number;
      /**
       * First-run tutorial: no ranking; victory at this t (§2.6).
       * @deprecated phase2c §2.6: the tutorial keeps no fish and flies none; both tutorial variants
       * open the victory at fx.win.replayVictoryAtMs.
       */
      readonly tutorialVictoryAtMs: number;
      /** Tutorial replay: no fish, no ranking; victory at this t (§2.6). Phase 2c: also the first-run tutorial. */
      readonly replayVictoryAtMs: number;
      /** Reduced-motion timeline (§2.7). */
      readonly reduced: {
        /** The ranking panel fades in at this t. */
        readonly rankingAtMs: number;
        /** The panel accepts a tap this long after it opened. */
        readonly tapMinMs: number;
        /** Static glow fade-in at t = winHappyDelayMs. [F0 addition: prose value, §2.7] */
        readonly glowInMs: number;
        /** "+3" label fade in, then out. [F0 addition: prose values, §2.7] */
        readonly plusLabelInMs: number;
        readonly plusLabelOutMs: number;
      };
    };
    readonly winHappyDelayMs: number;
    /** First post-win overlay: the ranking panel at 4.5 s (phase2b §2.2; was 800 for O3). */
    readonly winOverlayDelayMs: number;
    /** The victory screen's primary button turns active this long after it shows (phase2b §2.2; was 1000). */
    readonly winButtonDelayMs: number;
    readonly failOverlayDelayMs: number;
    readonly failButtonDelayMs: number;
    readonly sadCatsMs: number;
    readonly catDropMs: number;
    /**
     * @deprecated phase2d: the X pops in over fx.markPopMs (look-spec §1.10); the stroke draw-in is deleted.
     * Phase 2d.1: still unread; the new draw-in is the group fx.markDraw (helpers-spec §4.4).
     */
    readonly markDrawMs: number;
    readonly wrongShakeMs: number;
    readonly shakePx: number;
    /**
     * Phase 2 heart crack; kept in 2b for the falling halves of the heart break (phase2b §2.9).
     * @deprecated phase2c §1.3: the lives pill shake uses fx.lifeLossPillMs.
     */
    readonly heartCrackMs: number;
    readonly regionFadeMs: number;
    /** Done regions are mixed this far toward --page (02 §17.4). */
    readonly regionFadeMix: number;
    readonly overlayFadeMs: number;
    /** Max fade length with reduced motion on (02 §17.5). */
    readonly reducedMotionFadeMs: number;
    readonly toastMs: number;
    readonly catBlinkMinMs: number;
    readonly catBlinkMaxMs: number;
    /**
     * Phase 2c.1 §10.2: the level-points counter in the game screen's pills row. Each scoring cat
     * rolls the number (the old one slides out upward, the new one in from below) and bumps the
     * icon over rollMs, and a "+N" chip rises plusRisePx from the counter's top edge and fades over
     * plusMs (a newer chip replaces a running one). The chip sits in the gap under the top-bar
     * title, so its rise stays as small as fx.win.plusLabelRisePx (STATUS-2c L1). Reduced motion:
     * the number changes in place, no bump, and the chip fades in (reducedPlusInMs) and out
     * (reducedPlusOutMs) without rising.
     * Phase 2d.1 (helpers-spec §2.5, D-2d1-4): the Score column shows the "+N" over the tile, the star's
     * flight and a count-up (fx.points); it no longer reads rollMs, plusMs or plusRisePx. With reduced
     * motion the "+N" over the tile still fades in and out with reducedPlusInMs / reducedPlusOutMs.
     */
    readonly levelPoints: {
      /** @deprecated phase2d.1 (helpers-spec §2.5): not read by the Score column, which counts up over fx.points.countMs. */
      readonly rollMs: number;
      /** @deprecated phase2d.1 (helpers-spec §2.5): not read by the Score column (the "+N" pops over the tile, fx.points). */
      readonly plusMs: number;
      /** @deprecated phase2d.1 (helpers-spec §2.5): not read by the Score column (the "+N" pops over the tile, no rise). */
      readonly plusRisePx: number;
      /** Still read in 2d.1 (helpers-spec §2.5): the reduced-motion "+N" fades in over this … */
      readonly reducedPlusInMs: number;
      /** … and out over this, in place over the tile. */
      readonly reducedPlusOutMs: number;
    };
    /**
     * Phase 2d (look-spec §1.11; measured on the user's recording, 2026-10-10): the idle pulse of the
     * suggested helper. One cycle of periodMs: rise to peakScale with the warm glow (0 → 32 %), hold
     * (→ 36 %), fall (→ 69 %), rest (→ 100 %), forever; the count badge does not scale. `target`
     * picks the helper ([DECISION]). Reduced motion: no pulse.
     * Phase 2d.1 (helpers-spec §4.6, D-2d1-9; the user's recordings show no pulse at a level start):
     * the cycle is unchanged; with target 'auto' it plays only when all three new keys allow it.
     */
    readonly helperPulse: {
      readonly target: HelperPulseTarget;
      readonly periodMs: number;
      readonly peakScale: number;
      /**
       * Phase 2d.1 (helpers-spec §4.6): no board change (mark, unmark, cat, mistake) for this long since
       * the last one, the end of the board entry or the page becoming visible again before the suggested
       * helper pulses; the next board change stops it and restarts the idle time.
       */
      readonly idleMs: number;
      /** Phase 2d.1 (helpers-spec §4.6): a helper at 0 (the video badge) never pulses, and the other one does not take its place. */
      readonly needsStock: boolean;
      /** Phase 2d.1 (helpers-spec §4.6, critic): no pulse once a hint, the kitty or the mouse was used in this attempt (a Retry starts a new one). */
      readonly untilHelperUsed: boolean;
    };
    /**
     * Phase 2d (look-spec §1.6) [DECISION]: a head of the cat-heads pill pops and fills when its colour gets its cat.
     * Phase 2d.1 (helpers-spec §2.7, D-2d1-5; measured): 300 → 280. The head shows our cat face and a
     * colour dot and pops 0.56 → 1.20 at 83 ms → 1.0 at headFoundMs.
     */
    readonly headFoundMs: number;
    /**
     * Phase 2d (look-spec §1.10): a new X mark pops in (scale 0.6 → 1.06 → 1), replacing the stroke draw-in.
     * Phase 2d.1 (helpers-spec §1.5, §4.4; measured): 140 → 170, now the mouse's X only, from 1.15 to 1
     * under the leaving mouse; every other new X plays the draw-in (fx.markDraw).
     */
    readonly markPopMs: number;
    /**
     * Phase 2d (look-spec §1.12): the mouse's X marks pop in one after another, this far apart.
     * @deprecated phase2d.1 (helpers-spec §1.5, §7.2): the mouse visits its tiles one by one (fx.mouse); unread once 2d.1 is built.
     */
    readonly mouseStaggerMs: number;
    /**
     * Phase 2d (look-spec §1.14): the level-start toast. It slides in from the inline start over
     * inMs (delayMs after the board entry starts), holds holdMs, then drifts out to the inline start
     * at exitPxPerSec (linear; 100 px/s measured on the user's recording) × the layout scale.
     * Reduced motion: fade in, hold reducedHoldMs, fade out (fx.reducedMotionFadeMs each way).
     * @deprecated phase2d.1 (helpers-spec §5, §7.2): replaced by the two level-start tickers (fx.tickers); unread once 2d.1 is built.
     */
    readonly startToast: {
      readonly enabled: boolean;
      readonly delayMs: number;
      readonly inMs: number;
      readonly holdMs: number;
      readonly exitPxPerSec: number;
      readonly reducedHoldMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §4.4, D-2d1-8; critic re-measure on the user's recording): the draw-in of
     * every new X from a tap, a paint or Apply (the mouse's X pops instead, fx.markPopMs). Per tile, all
     * new tiles of an action together, t from the action: the tile squishes 0.90 → 1 over squishMs; bar
     * "\" scales about the X's centre 0.3 → 1 over stroke1Ms; bar "/" is then revealed from its
     * top-right tip over stroke2Ms; the X group scales 1 → overshoot by stroke1Ms, holds, and is back
     * to 1 at settleMs. The wrong X has no draw-in. Reduced motion: the X fades in over
     * fx.reducedMotionFadeMs. (The 2b key fx.markDrawMs stays @deprecated and unread.)
     */
    readonly markDraw: {
      readonly squishMs: number;
      readonly stroke1Ms: number;
      readonly stroke2Ms: number;
      readonly overshoot: number;
      readonly settleMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §1.5, D-2d1-1; measured): the mouse visits its tiles in pick order. Per
     * visit (t = 0: the mouse appears on the tile): it scales 0.5 → 1 over appearMs; at dwellMs its X
     * pops in under it (fx.markPopMs) and it leaves over exitMs; the next visit starts at
     * dwellMs + exitMs (mouseVisitMs, 935). Reduced motion: the X's fade in together.
     */
    readonly mouse: {
      readonly appearMs: number;
      readonly dwellMs: number;
      readonly exitMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §2.4, D-2d1-3; measured): the board sequence of every correct cat (the
     * kitty's, a hint's, the player's). The cat pops, is held at 1.25 × its size and winks until
     * celebrateUntilMs, and is back at its resting size by settleMs. `shards` two-tone chunks burst
     * from the tile and are gone by shardLifeMs (the screen fx layer). Reduced motion: none of it.
     */
    readonly catPlaced: {
      readonly celebrateUntilMs: number;
      readonly settleMs: number;
      readonly shards: number;
      readonly shardLifeMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §2.5, D-2d1-4; measured): on POINTS the "+N" pops one pitch above the
     * cat's tile; a star is born on it at starAtMs, flies to the Score over flightMs (quadratic Bézier)
     * and lands as a sparkle burst lasting burstMs, while the Score counts up to the new total over
     * countMs (quadratic ease-out, no bump). Reduced motion: no star, burst or count-up
     * (fx.levelPoints.reducedPlusInMs / reducedPlusOutMs for the "+N").
     */
    readonly points: {
      readonly starAtMs: number;
      readonly flightMs: number;
      readonly countMs: number;
      readonly burstMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §4.1–§4.3, D-2d1-6): a row, column or colour region that an action
     * completes (UNITS_DONE). Its tiles bump in a wave, one waveStepMs apart from the end nearer the
     * anchor, and our "Done!" label under the anchor tile has faded out by labelMs. Reduced motion: no
     * wave; the label fades in and out in place.
     */
    readonly unitDone: {
      readonly waveStepMs: number;
      readonly labelMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §3.2–§3.3, D-2d1-7; measured): the hint overlay (O1). Its dim fades in
     * linearly over dimMs; the ghost X of the i-th Empty effect cell (ghostOrder) appears at
     * ghostFirstMs + i × ghostStaggerMs after the open and pops over ghostPopMs. Reduced motion: the
     * ghosts appear together at ghostFirstMs without the pop.
     */
    readonly hint: {
      readonly dimMs: number;
      readonly ghostFirstMs: number;
      readonly ghostStaggerMs: number;
      readonly ghostPopMs: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §5, D-2d1-12; the user's stills): the two level-start tickers that replace
     * fx.startToast. Line 2 starts delayMs after the board entry starts and line 1 lead × crossMs later;
     * each line crosses from the inline-end edge of the viewport to past its inline-start edge
     * (vw + its width) linearly in crossMs. Reduced motion: both fade in at the column's inline start,
     * hold reducedHoldMs, fade out. `enabled: false` shows none.
     */
    readonly tickers: {
      readonly enabled: boolean;
      readonly delayMs: number;
      readonly crossMs: number;
      readonly lead: number;
      readonly reducedHoldMs: number;
    };
  };
  readonly save: {
    readonly localDebounceMs: number;
    readonly cloudDebounceMs: number;
    readonly storageKey: string;
    readonly corruptKeyPrefix: string;
    readonly corruptKeep: number;
    /** FB player-data key (05 §7). */
    readonly cloudKey: string;
    /** setDataAsync NETWORK_FAILURE backoff (05 §7). */
    readonly cloudRetryDelaysMs: readonly number[];
    /** FB: getDataAsync wait at boot; on timeout the session keeps the local copy and skips cloud writes (05 §7). */
    readonly cloudLoadTimeoutMs: number;
    /**
     * FB: after a failed or timed-out boot read, the cloud copy is read again in the background on
     * this schedule (the last delay repeats) until it arrives; the app then merges it and cloud
     * writes start (05 §7 "the cloud merge follows", PLAT-1). [platform addition]
     */
    readonly cloudLateRetryDelaysMs: readonly number[];
  };
  readonly timer: { readonly tickMs: number };
  readonly hint: {
    /** p95 budget for main-thread getHintStep before moving to the worker (03 §6, §10). */
    readonly mainThreadBudgetMs: number;
  };
  readonly audio: {
    /** Master peak level in dBFS (02 §16). */
    readonly masterDb: number;
    readonly markPitchJitter: number;
    /** Each arriving fish's "plink" is this many semitones above the previous one (phase2b §2.2). */
    readonly fishPlinkStepSemitones: number;
  };
  /** navigator.vibrate patterns in ms (02 §16). */
  readonly haptics: {
    readonly mark: number;
    readonly cat: number;
    readonly mistake: readonly number[];
    readonly heartLast: number;
    readonly win: readonly number[];
    readonly kitty: number;
    readonly ui: number;
    /** One pulse per arriving fish (phase2b §2.2). */
    readonly fish: number;
  };
  /**
   * Responsive layout (02 §19) and board rendering (02 §17.4, §18). CSS px.
   * Phase 2d (look-spec §1.1, §1.8, §1.10): the game screen follows layout.game (a vertical stack
   * measured on the user's recording at 402 CSS px, scaled by s) and the X follows layout.mark. The
   * keys marked "@deprecated phase2d" below are unread once 2d is built (the rule never removes a key).
   */
  readonly layout: {
    /** @deprecated phase2d: the game column is layout.game.refWidth × s (cardMargin at the sides). */
    readonly gutter: number;
    /** @deprecated phase2d: layout.game.refWidth × layout.game.maxScale. */
    readonly colMax: number;
    /** @deprecated phase2d: layout.game.bar × s. */
    readonly topBar: number;
    /** @deprecated phase2d: layout.game.pills × s. */
    readonly pills: number;
    /** @deprecated phase2d: layout.game.rules × s (the rule cards). */
    readonly chips: number;
    /** @deprecated phase2d: layout.game.tools × s. */
    readonly tools: number;
    /** @deprecated phase2d: layout.game.boardToTools / toolsToBanner / bottom × s. */
    readonly toolsGap: number;
    /** @deprecated phase2d: the measured gaps of layout.game × s. */
    readonly vGap: number;
    /** @deprecated phase2d: the measured gaps of layout.game × s. */
    readonly vGapCount: number;
    /** @deprecated phase2d: layout.game.cardPad × s (rounded). */
    readonly boardPad: number;
    /** @deprecated phase2d: layout.game.cardRadius × s. */
    readonly boardRadius: number;
    /** @deprecated phase2d: compact = s < layout.game.compactScale. */
    readonly compactHeight: number;
    /** @deprecated phase2d: everything scales with s; no separate compact sizes. */
    readonly compactPills: number;
    /** @deprecated phase2d: everything scales with s; no separate compact sizes. */
    readonly compactChips: number;
    readonly fbSafeZonePx: number;
    readonly rotateMaxHeight: number;
    readonly minViewportW: number;
    readonly minViewportH: number;
    /** Tile corner radius as a fraction of the slot (phase2b §1.5: 0.2). @deprecated phase2d: layout.game.tileRadiusFraction (of the tile edge). */
    readonly cellRadiusFraction: number;
    /** @deprecated phase2b §1.8: region-aware insets are deleted; not read after 2b. Use insetPx / insetSmallPx. */
    readonly insetSamePx: number;
    /** @deprecated phase2b §1.8: region-aware insets are deleted; not read after 2b. Use insetPx / insetSmallPx. */
    readonly insetDiffPx: number;
    /** Even gutters (phase2b §1.5): every tile inset this much on all sides (a 4 px gutter) … @deprecated phase2d: gap = round(slot × layout.game.gapFraction), inset = gap / 2. */
    readonly insetPx: number;
    /** … or this much (a 3 px gutter) when the slot is below insetSmallBelowSlot. @deprecated phase2d: layout.game.gapFraction. */
    readonly insetSmallPx: number;
    /** @deprecated phase2d: layout.game.gapFraction. */
    readonly insetSmallBelowSlot: number;
    /** Cat size as a fraction of the slot (phase2b §1.5: 0.84). */
    readonly catScale: number;
    /** X mark size: path a→100−a with a = (1 − markScale)/2 × 100 (phase2b §1.5: 0.54 → 23…77). @deprecated phase2d: layout.mark.armFraction. */
    readonly markScale: number;
    /** White X stroke on the 100-unit box ÷ 100 (phase2b §1.5: 12 units). @deprecated phase2d: layout.mark.barFraction. */
    readonly markStrokeFraction: number;
    /** X opacity: 1 = the white X (phase2b §1.5). The 0.7 dark-ink X is retired (§1.8). */
    readonly markOpacity: number;
    /** X edge underlay: extra stroke per side ÷ 100 (12 + 2 × 4 = 20 units), phase2b §1.5. @deprecated phase2d: layout.mark.edgeFraction (shown only with colour patterns on). */
    readonly markEdgeFraction: number;
    /** X edge colour: mixHex(tile, --ink, markEdgeMix) per palette index (ui/art/palette.ts xEdgeColor), §1.5. @deprecated phase2d: layout.mark.edgeMix toward --ink-deep. */
    readonly markEdgeMix: number;
    readonly wrongRingPx: number;
    readonly patternScale: number;
    readonly focusRingPx: number;
    readonly hintDim: number;
    /** Colour-pattern glyph opacity (--ink) on a tile, and on a faded (done) tile: both ≥ 3:1 (02 §18, palette-check). [ui addition] */
    readonly patternOpacity: number;
    readonly patternOpacityDone: number;
    /** Smallest drawn glyph box (CSS px): small slots scale the 22 % glyph up to this (11×11 / 12×12 on phones). [ui addition] */
    readonly patternMinPx: number;
    /**
     * Phase 2d (look-spec §1.1, §1.8; measured on the user's recording at a 402 × 874 CSS px viewport,
     * user decision 2026-10-10). The game screen is one column stacked top-down at scale
     *   s = clamp(min(min(vw, refWidth × maxScale) / refWidth, (A − B) / K), minScale, maxScale)
     * with A = vh − safeTop − safeBottom, B = ads.banner.bannerPx when the banner band is reserved
     * (else 0) and K = the sum of the rows and gaps below (toolsToBanner only with the band) plus the
     * square board card (refWidth − 2 × cardMargin). Every value here is CSS px at s = 1, except the
     * fractions. Spare height goes above the bar up to topSpareMax × s, the rest below.
     */
    readonly game: {
      readonly refWidth: number;
      readonly minScale: number;
      readonly maxScale: number;
      /** Below this scale the rule cards show their diagrams only (their text stays for screen readers). */
      readonly compactScale: number;
      readonly topSpareMax: number;
      /** Top bar band (back and gear discs centred at bar / 2). */
      readonly bar: number;
      readonly barToPills: number;
      /** Heads pill and fish pill height. */
      readonly pills: number;
      readonly pillsToRules: number;
      /** The white rules container (three rule cards). */
      readonly rules: number;
      /**
       * At a text scale above 1 the rules row grows by min(rulesGrowMax, textScale × 1.15) (not in compact mode)
       * and the bar by min(rulesGrowMax, textScale) (look-spec §1.1 barH); the board gives up the space.
       */
      readonly rulesGrowMax: number;
      readonly rulesToBoard: number;
      /** Board card bottom → helper disc top. */
      readonly boardToTools: number;
      /** Helper disc diameter (the row's height; the badges reach into boardToTools). */
      readonly tools: number;
      /** Helper discs → banner, only when the banner band is reserved. */
      readonly toolsToBanner: number;
      /** Below the last row (the banner or the helpers), above safeBottom. */
      readonly bottom: number;
      /** Board card side margin; the card is refWidth − 2 × cardMargin wide at s = 1. */
      readonly cardMargin: number;
      /** Card edge → first slot edge (the first tile edge adds half a gap). Rounded to whole px, ≥ 3. */
      readonly cardPad: number;
      readonly cardRadius: number;
      /** Gap between tiles ÷ slot: gap = max(1, round(slot × gapFraction)); every tile is inset gap / 2. */
      readonly gapFraction: number;
      /** Tile corner radius ÷ tile edge (slot − gap). */
      readonly tileRadiusFraction: number;
    };
    /**
     * Phase 2d (look-spec §1.10; measured on the user's recording): the X is two white rounded bars
     * crossing at ±45°, as fractions of the cell's 100-unit box (the slot): each bar armFraction long
     * and barFraction thick with corners of cornerFraction; no outline by default. With colour patterns
     * on, an edge underlay (each bar grown by edgeFraction per side) in mixHex(tile, --ink-deep, edgeMix).
     */
    readonly mark: {
      readonly armFraction: number;
      readonly barFraction: number;
      readonly cornerFraction: number;
      readonly edgeFraction: number;
      readonly edgeMix: number;
    };
    /**
     * Phase 2d.1 (helpers-spec §3.2, D-2d1-7; measured on the user's recording at 402 CSS px): the hint
     * overlay's card and Apply pill, CSS px at s = 1 (× s), placed against the board card's rect. The
     * card is cardW wide and at least cardMinH tall, centred on the column with its bottom cardGap above
     * the board card's top (it grows upward). Apply is applyW × applyH, centred on the column with its
     * top applyGap below the board card's bottom.
     */
    readonly hint: {
      readonly cardW: number;
      readonly cardMinH: number;
      readonly cardGap: number;
      readonly applyW: number;
      readonly applyH: number;
      readonly applyGap: number;
    };
  };
  /** Offline generator and runtime substitute/endless generation (03 §4.5, §8.3). */
  readonly gen: {
    readonly maxAttempts: number;
    readonly repairMaxIter: number;
    /** Growth for 'mixed': eden when rng.int(edenOneIn) === 0 (25 %), else balanced. */
    readonly edenOneIn: number;
    readonly minRegionSize: number;
    readonly minRegionFromN: number;
    /** Levels ≤ this keep minRegion 1 (tutorial and levels ≤ 6). */
    readonly singleCellRegionsUpToLevel: number;
    readonly maxRegionFactor: number;
    /** Effort-sort noise: key = e × (noiseBase + rng.int(noiseSpan)) (03 §8.3). */
    readonly sortNoiseBase: number;
    readonly sortNoiseSpan: number;
    readonly version: string;
  };
  /** FBInstant.logEvent limits (05 §10, 02 §20). */
  readonly analytics: {
    readonly nameMin: number;
    readonly nameMax: number;
    readonly maxParams: number;
    readonly keyMin: number;
    readonly keyMax: number;
    readonly valueMaxLen: number;
  };
  /** Boot sequence caps (04 §5.1). [app addition] */
  readonly boot: {
    /** Longest wait for document.fonts.ready; the font never blocks boot on failure (04 §5.1). */
    readonly fontTimeoutMs: number;
    /** Longest wait for restore-rule validation at launch; slower checks run when the board is opened (02 §15). */
    readonly restoreTimeoutMs: number;
    /**
     * Longest wait for the current level's pack at launch (04 §5.1 ensurePackFor). The fetch goes on
     * in the background and getLevel() waits for it behind the loading indicator (RP-1). [boot addition]
     */
    readonly packTimeoutMs: number;
    /** platform.init() / start() are retried once after this delay before boot gives up (PLAT-8). [boot addition] */
    readonly platformRetryDelayMs: number;
    /**
     * First run only: longest wait for the lazy overlay chunk (it holds the tutorial coach, O8), side
     * by side with the pack and font waits, so the first board shows with its coach (04 §9). [boot addition]
     */
    readonly overlayTimeoutMs: number;
  };
  /** Loading indicator (lead decision, Phase 2 integration). [app addition] */
  readonly loading: {
    /** Opening a level or daily that takes longer than this (pack fetch, on-device generation) shows the indicator. */
    readonly indicatorDelayMs: number;
    /** Last resort: a level or daily still not ready after this goes back Home with a toast (04 §8). [app addition] */
    readonly failSafeMs: number;
  };
  /** Lazy JS chunks (04 §9): a failed import is retried with a cache-busting URL (04 §8). [app addition] */
  readonly chunks: {
    /** Backoff before each retry; its length is the number of retries. */
    readonly retryDelaysMs: readonly number[];
    /** Per-attempt cap, so a stalled download cannot hang the caller. */
    readonly timeoutMs: number;
  };
  /** Engine worker (04 §5.5). [app addition] */
  readonly worker: {
    /** Deadline for the worker's start-up and for each call; on expiry the worker is dropped and work runs on the main thread. */
    readonly callTimeoutMs: number;
  };
  /**
   * Fish, the soft currency (phase2b §2.8). Three fish per win; bonuses add a number, not more fish.
   * @deprecated phase2c §5: fish are the LIVES (hearts.perAttempt, revive.heartsRestored) and the fish
   * kept at a win are leaderboard points (`period`). The wallet, its earn table and its cap are gone;
   * nothing reads this group after 2c (group rewards: groups.placeHints).
   */
  readonly fish: {
    readonly perWin: number;
    readonly hardBonus: number;
    readonly dailyBonus: number;
    /** First-run tutorial (the replay earns nothing). */
    readonly tutorial: number;
    /** Group challenge, rank mode: non-winners with wins ≥ 1 (phase2b §5.6). */
    readonly groupParticipation: number;
    /** Wallet cap. */
    readonly max: number;
  };
  /**
   * Fish swaps [DECISION: default, user may change] (phase2b §2.8, §8.5). Revives are never for sale.
   * @deprecated phase2c §5: no fish swaps; nothing reads this group after 2c.
   */
  readonly shop: {
    readonly hintFish: number;
    readonly kittyFish: number;
  };
  /** Paw points per win (phase2b §5.3): every result is a multiple of 5. */
  readonly points: {
    /** Base = perSize × n. @deprecated phase2c §3: levelPoints.perSize. */
    readonly perSize: number;
    /** Hard level: base × hardMultiplier. @deprecated phase2c §3: levelPoints.hardMultiplier. */
    readonly hardMultiplier: number;
    /** 0 mistakes and 0 revives. @deprecated phase2c §3: replaced by the perfect-streak bonus. */
    readonly flawless: number;
    /** 0 hints and 0 kitties. @deprecated phase2c §3: hints and kitties never change level points. */
    readonly unaided: number;
    /** @deprecated phase2c §3: one formula for every scored mode. */
    readonly daily: number;
    /** @deprecated phase2c §3: one formula for every scored mode. */
    readonly event: number;
    /**
     * points.total cap (scores stay < 2³¹). Phase 2c: still the cap of the lifetime level-points total.
     * Phase 2c.1 §3.2.4: points.total = the sum of the level totals of counted wins (one level ≤ 13 248).
     */
    readonly max: number;
  };
  /**
   * LEVEL POINTS. Phase 2c.1 (fish-lives-spec §3.1; the user's exact rule, first-hand, Play Store
   * Meowdoku, 2026-10-10): the points belong to ONE level and every level and every Retry starts at
   * 0. Each correct cat found adds firstIncrement + step × (s − 1), where s counts the correct cats in
   * a row since the level started or since the last mistake (s = 1 for the first such cat):
   * 96 × (5 + s) = 576, 672, 768, … Running totals of an unbroken run: 576, 1 248, 2 016, 2 880,
   * 3 840, 4 896, 6 048, 7 296, 8 640, 10 080. A mistake takes nothing away; it resets s, so the next
   * correct cat adds firstIncrement again. Cats placed by a hint or the kitty count like the player's.
   * No Hard multiplier and no cap (s ≤ n ≤ 12, so one level scores at most 13 248).
   * Phase 2c (superseded): a per-win formula perSize × n (× hardMultiplier) + streakStep ×
   * min(perfect wins in a row, streakCap); those four keys are @deprecated and no longer read.
   */
  readonly levelPoints: {
    /** @deprecated phase2c.1 §3.1: level points are earned per cat (firstIncrement, step); not read. */
    readonly perSize: number;
    /** @deprecated phase2c.1 §3.1: the user's rule has no Hard multiplier; not read. */
    readonly hardMultiplier: number;
    /** @deprecated phase2c.1 §3.2: the cross-level perfect streak is gone (the streak counts cats inside a level); not read. */
    readonly streakStep: number;
    /** @deprecated phase2c.1 §3.2: no cap; not read. */
    readonly streakCap: number;
    /**
     * Modes whose correct cats score level points; the HUD counter shows only there
     * [DECISION: default, user may change]. The tutorial never scores (it is not a ScoredMode).
     */
    readonly modes: readonly ScoredMode[];
    /** Points of the 1st correct cat in a row (s = 1): 576 = 96 × (5 + 1). User, first-hand, 2026-10-10. */
    readonly firstIncrement: number;
    /** Each further correct cat in a row adds this much more than the one before (s ≥ 2): 96. User, first-hand, 2026-10-10. */
    readonly step: number;
  };
  /**
   * Phase 2c §4: LEADERBOARD POINTS [DECISION: default, user may change]. A counted win in a mode of
   * `modes` adds the fish (lives) left at the win × pointsPerFish to the current period's total, which
   * starts again at 0 with every new UTC period. The FB board `rank.boards.period` ranks that total
   * per period (band encoding, phase2c §4.3).
   */
  readonly period: {
    /** UTC calendar period: 'week' starts Monday 00:00 UTC, 'day' at 00:00 UTC, 'month' on the 1st 00:00 UTC. */
    readonly kind: PeriodKind;
    readonly pointsPerFish: number;
    readonly modes: readonly ScoredMode[];
    /** Cap of one period's total; always below the score encoding's span (phase2c §4.3). */
    readonly max: number;
  };
  /** Limited-time events (phase2b §4). Times use the device clock. */
  readonly events: {
    /** teaserEvent(): the next event within this many hours shows a "Starts in" card (§4.4). */
    readonly teaseHours: number;
    /** The card says "Ends soon!" in the last this-many hours (§4.6). */
    readonly cardEndsSoonHours: number;
  };
  /** Rankings (phase2b §2.4, §5). Never fabricate a player, rank, score or row. */
  readonly rank: {
    /** Deadline for every provider call, counted from WON (§2.2, §5.4). */
    readonly fetchTimeoutMs: number;
    /** Rows shown in the panel list. */
    readonly topCount: number;
    /** Entries fetched for the overlay list. */
    readonly fetchCount: number;
    readonly panelPopMs: number;
    readonly panelOutMs: number;
    /** The panel accepts a tap/Enter/Space/Esc this long after it opened (§2.2 t = 5 700). */
    readonly panelTapMinMs: number;
    /** "Tap to keep going" pulse (opacity .55 ↔ 1 is CSS-only). */
    readonly tapPulseMs: number;
    /** Client-side sanity limits (§5.3): at most one submission per interval; solves outside min…max are not submitted. */
    readonly submitMinIntervalMs: number;
    readonly minSolveMs: number;
    readonly maxSolveMs: number;
    /** daily_fastest dayIndex = whole days from this date to the daily's date key (§5.3). */
    readonly dailyEpoch: string;
    /**
     * Phase 2c §4.3: period index 0 is the UTC period that contains this date (a Monday, so week 0
     * starts on it); day indices count days from it, month indices months from its month.
     */
    readonly periodEpoch: string;
    /**
     * Board keys (§5.3): event boards are eventPrefix + the event id with '-' → '_'.
     * Phase 2c §4: `period` (the per-period leaderboard points board) is THE post-win board in every
     * mode; `points` (paw_points) is retired (never submitted or read); `daily` only with rank.dailyBoard.
     */
    readonly boards: { readonly points: 'paw_points'; readonly daily: 'daily_fastest'; readonly eventPrefix: 'event_'; readonly period: 'period_points' };
    /**
     * Phase 2c §4.4 [DECISION: default, user may change]: keep submitting and showing daily_fastest
     * (the hub's "Today" tab). Off: the original's leaderboard is the period points board.
     */
    readonly dailyBoard: boolean;
    /** Where the FB overlay list goes: 'fullscreen' until §14 G3 shows a rect placement works. */
    readonly overlayPlacement: 'fullscreen' | 'rect';
    /** Without a provider (web) the panel still shows, with personal records (§2.4). */
    readonly showPanelWithoutProvider: boolean;
  };
  /** Group challenges (FB tournaments, phase2b §5.6), behind flag groupChallenges. */
  readonly groups: {
    readonly durationH: number;
    /** 'participation' (default; needs no standings API) or 'rank' (only if §14 G2 finds one). */
    readonly rewardMode: 'participation' | 'rank';
    readonly minWinsForReward: number;
    readonly rewardKitties: number;
    /** Total with the rewarded video (not rewardKitties + this). */
    readonly rewardKittiesWithAd: number;
    /** Rows shown (overlay view only). */
    readonly maxShown: number;
    /** save.groups entries kept (oldest endsAt dropped). */
    readonly keep: number;
    /** Phase 2c §5.6: rank mode, non-winners with wins ≥ 1 get this many hints (was fish.groupParticipation fish). */
    readonly placeHints: number;
  };
  /** FB payments (phase2b §8). */
  readonly iap: {
    /** The shop shows "Getting the shop ready…" this long before shop.unavailable (§8.4). */
    readonly readyTimeoutMs: number;
    readonly catalogCacheMs: number;
    /** purchases.tokens ledger length (newest kept). */
    readonly tokensKept: number;
    /** true: record, grant, save, then consume (§8.4). false: consume first (G5 fallback). */
    readonly grantBeforeConsume: boolean;
    /** 'consume': No Ads consumed and kept as purchases.noAds. 'keep': never consumed (G5 alternative). */
    readonly removeAdsMode: 'consume' | 'keep';
    /**
     * @deprecated phase2c §5.3: the 2b catalogue (with the fish packs). 2c code reads iap.catalog
     * (what is sold) and iap.retired (what the ledger and a boot restore still recognise).
     */
    readonly products: readonly IapProductDef[];
    /** Phase 2c §5.3: the products on sale, in shop order (No Ads, hint pack, kitty pack). */
    readonly catalog: readonly IapProductDef[];
    /**
     * Phase 2c §5.3: products that are no longer sold but may still sit in a purchase ledger or come
     * back unconsumed from a boot restore. Their grant is a compensation in hints and kitties (the
     * fish they gave, at the old 15 / 30 swap rates). Never listed in the shop or the catalogue.
     */
    readonly retired: readonly IapProductDef[];
  };
  /** Localization (phase2b §6). */
  readonly i18n: {
    /** Every locale with a catalogue; dev, e2e and web preview builds bundle all of them (§6.7). */
    readonly locales: readonly LocaleId[];
    readonly fallback: LocaleId;
    /** Right-to-left locales (§6.5). */
    readonly rtl: readonly LocaleId[];
    /** After start(), the resolved locale's chunk may delay the first route this long (§6.3). */
    readonly localeTimeoutMs: number;
    /**
     * The locales a release build (`--mode release` / `release-fbig`) bundles [DECISION: default,
     * user may change] (§6.7). Always includes 'en'; a locale joins when the user approves it.
     */
    readonly releaseLocales: readonly LocaleId[];
  };
  /**
   * Settings → Feedback (review PAR-5; the original sends players to "Settings → Feedback", 01 §14.2).
   * `feedbackUrl` is an https: or mailto: link; empty hides the row. On FBIG the row also needs
   * `feedbackOnFbig` (off until Meta's external-link rules are checked, parity-spec §14).
   */
  readonly support: {
    readonly feedbackUrl: string;
    readonly feedbackOnFbig: boolean;
  };
  /**
   * Phase 2d (look-spec §1.15) [DECISION]: the red dot on the Settings gear marks something in
   * Settings the player has not seen. It shows while the save's seen marker (SaveData.ext
   * 'settingsSeen', a number) is below `version`, and opening Settings sets the marker to `version`.
   * Raise `version` when a release adds or changes a Settings row; 0 never shows the dot.
   */
  readonly settingsDot: { readonly version: number };
}

export const cfg: GameConfig = deepFreeze({
  hearts: { perAttempt: 3 },
  input: {
    doubleTapMs: 300,
    dragStartMinPx: 8,
    dragStartCellFraction: 0.2,
    cellLockAfterCatMs: 300,
    paintSoundThrottleMs: 40,
  },
  hints: { startStock: 5, perRewardedAd: 1 },
  kitty: { startStock: 3, perRewardedAd: 1, revealMs: 820 },
  mouse: { enabled: true, cells: 3 },
  revive: { maxPerAttempt: 1, heartsRestored: 1 },
  ads: {
    enabled: true,
    readyTimeoutMs: 4000,
    showWatchdogMs: 120_000,
    interstitial: {
      minCompletedLevels: 10,
      cooldownSec: [
        { fromDay: 0, sec: 120 },
        { fromDay: 2, sec: 100 },
        { fromDay: 7, sec: 90 },
      ],
      sessionGraceSec: 60,
      triggers: ['next_level', 'retry', 'daily_done', 'event_next'],
    },
    rewarded: { resetsInterstitialClock: true, placements: ['hint', 'kitty', 'revive', 'group_double', 'mouse'] },
    banner: {
      enabled: true,
      fromCompletedLevels: 10,
      screens: ['home', 'victory', 'event'],
      position: 'bottom',
      reservePx: 58,
      minReloadSec: 60,
      buttonClearancePx: 16,
      duringPlay: true,
      bannerPx: 50,
      hideDuringHint: true,
    },
    unsupportedFallback: { cooldownSec: 600 },
    mock: { durationMs: 1500 },
    reloadDelaysMs: [5000, 30_000, 120_000],
    loadTimeoutMs: 12_000,
  },
  daily: { unlockAfterLevel: 20, firstPackMonth: '2026-10' },
  levels: {
    shipped: 1000,
    hardEvery: 10,
    hardFrom: 30,
    prefetchAhead: 20,
    packSize: 100,
    fetchRetryDelaysMs: [500, 2000],
    fetchTimeoutMs: 5000,
  },
  fx: {
    boardEntryMs: 700,
    boardEntryStaggerMs: 18,
    boardEntryCardMs: 250,
    boardEntryRisePx: 24,
    boardEntryWaveStartMs: 80,
    boardEntryTileMs: 220,
    boardEntryWaveBudgetMs: 400,
    screenOutMs: 160,
    screenInMs: 240,
    screenInDelayMs: 80,
    screenSlidePx: 16,
    screenBackInMs: 200,
    screenReducedMs: 120,
    heartBreakMs: 700,
    lifeLossMs: 700,
    lifeLossPillMs: 400,
    catBreatheMs: 2800,
    catBreatheScale: 0.02,
    earFlickMinMs: 8000,
    earFlickMaxMs: 14_000,
    earFlickMs: 160,
    mascotHeadTiltMinMs: 6000,
    mascotHeadTiltMaxMs: 10_000,
    victoryRaysTurnMs: 20_000,
    win: {
      glowInMs: 300,
      glowSettleMs: 600,
      glowStaggerMs: 40,
      glowSettleOpacity: 0.7,
      glowScale: 1.3,
      fishPillInAtMs: 1000,
      fishPillFadeMs: 200,
      fishAtMs: 1200,
      fishStaggerMs: 150,
      fishPopMs: 220,
      fishHoldMs: 250,
      fishFlightMs: 800,
      fishArcLift: 0.35,
      fishArcSpread: 0.1,
      fishPathSamples: 12,
      fishEndScale: 0.6,
      fishSizeFraction: 0.5,
      fishMinPx: 22,
      fishMaxPx: 36,
      fishTrailDots: 5,
      fishTrailMs: 300,
      counterBumpMs: 360,
      plusLabelMs: 700,
      plusLabelRisePx: 6,
      bonusLabelAtMs: 2900,
      scrimAtMs: 4200,
      scrimFadeMs: 300,
      panelAfterLastMs: 1950,
      scrimLeadMs: 300,
      tutorialVictoryAtMs: 3300,
      replayVictoryAtMs: 1200,
      reduced: { rankingAtMs: 1200, tapMinMs: 600, glowInMs: 150, plusLabelInMs: 150, plusLabelOutMs: 600 },
    },
    winHappyDelayMs: 300,
    winOverlayDelayMs: 4500,
    winButtonDelayMs: 600,
    failOverlayDelayMs: 800,
    failButtonDelayMs: 600,
    sadCatsMs: 1500,
    catDropMs: 280,
    markDrawMs: 120,
    wrongShakeMs: 300,
    shakePx: 6,
    heartCrackMs: 400,
    regionFadeMs: 400,
    regionFadeMix: 0.45,
    overlayFadeMs: 200,
    reducedMotionFadeMs: 150,
    toastMs: 2500,
    catBlinkMinMs: 3000,
    catBlinkMaxMs: 7000,
    levelPoints: { rollMs: 360, plusMs: 700, plusRisePx: 6, reducedPlusInMs: 150, reducedPlusOutMs: 600 },
    helperPulse: { target: 'auto', periodMs: 1500, peakScale: 1.08, idleMs: 5000, needsStock: true, untilHelperUsed: true },
    headFoundMs: 280,
    markPopMs: 170,
    mouseStaggerMs: 90,
    startToast: { enabled: true, delayMs: 150, inMs: 300, holdMs: 1200, exitPxPerSec: 100, reducedHoldMs: 1500 },
    markDraw: { squishMs: 80, stroke1Ms: 70, stroke2Ms: 130, overshoot: 1.1, settleMs: 250 },
    mouse: { appearMs: 115, dwellMs: 850, exitMs: 85 },
    catPlaced: { celebrateUntilMs: 816, settleMs: 1400, shards: 10, shardLifeMs: 650 },
    points: { starAtMs: 783, flightMs: 530, countMs: 350, burstMs: 650 },
    unitDone: { waveStepMs: 33, labelMs: 720 },
    hint: { dimMs: 300, ghostFirstMs: 333, ghostStaggerMs: 60, ghostPopMs: 500 },
    tickers: { enabled: true, delayMs: 150, crossMs: 9000, lead: 0.086, reducedHoldMs: 3000 },
  },
  save: {
    localDebounceMs: 400,
    cloudDebounceMs: 3000,
    storageKey: 'mewdoku.save.v1',
    corruptKeyPrefix: 'mewdoku.save.corrupt.',
    corruptKeep: 2,
    cloudKey: 'save',
    cloudRetryDelaysMs: [1000, 3000, 10_000],
    cloudLoadTimeoutMs: 4000,
    cloudLateRetryDelaysMs: [5000, 15_000, 30_000, 60_000],
  },
  timer: { tickMs: 1000 },
  hint: { mainThreadBudgetMs: 30 },
  audio: { masterDb: -12, markPitchJitter: 0.03, fishPlinkStepSemitones: 2 },
  haptics: {
    mark: 6,
    cat: 14,
    mistake: [30, 40, 30],
    heartLast: 60,
    win: [20, 30, 20, 30, 40],
    kitty: 14,
    ui: 4,
    fish: 8,
  },
  layout: {
    gutter: 16,
    colMax: 480,
    topBar: 56,
    pills: 44,
    chips: 40,
    tools: 64,
    toolsGap: 16,
    vGap: 12,
    vGapCount: 4,
    boardPad: 10,
    boardRadius: 18,
    compactHeight: 640,
    compactPills: 36,
    compactChips: 36,
    fbSafeZonePx: 64,
    rotateMaxHeight: 480,
    minViewportW: 320,
    minViewportH: 568,
    cellRadiusFraction: 0.2,
    insetSamePx: 1.5,
    insetDiffPx: 3.5,
    insetPx: 2,
    insetSmallPx: 1.5,
    insetSmallBelowSlot: 30,
    catScale: 0.84,
    markScale: 0.54,
    markStrokeFraction: 0.12,
    markOpacity: 1,
    markEdgeFraction: 0.04,
    markEdgeMix: 0.7,
    wrongRingPx: 2,
    patternScale: 0.22,
    focusRingPx: 3,
    hintDim: 0.55,
    patternOpacity: 0.85,
    patternOpacityDone: 0.65,
    patternMinPx: 7,
    game: {
      refWidth: 402,
      minScale: 0.6,
      maxScale: 1.2,
      compactScale: 0.85,
      topSpareMax: 62,
      bar: 52,
      barToPills: 10.3,
      pills: 31.3,
      pillsToRules: 8.3,
      rules: 60.3,
      rulesGrowMax: 2,
      rulesToBoard: 25.7,
      boardToTools: 53,
      tools: 60.3,
      toolsToBanner: 23.4,
      bottom: 12.3,
      cardMargin: 5.67,
      cardPad: 5.17,
      cardRadius: 11.6,
      gapFraction: 0.079,
      tileRadiusFraction: 0.11,
    },
    mark: { armFraction: 0.69, barFraction: 0.182, cornerFraction: 0.06, edgeFraction: 0.035, edgeMix: 0.85 },
    hint: { cardW: 334.4, cardMinH: 70.3, cardGap: 5.9, applyW: 278.7, applyH: 59.3, applyGap: 31 },
  },
  gen: {
    maxAttempts: 5000,
    repairMaxIter: 400,
    edenOneIn: 4,
    minRegionSize: 2,
    minRegionFromN: 6,
    singleCellRegionsUpToLevel: 6,
    maxRegionFactor: 2.5,
    sortNoiseBase: 90,
    sortNoiseSpan: 21,
    version: 'mewdoku-gen/1.0.0',
  },
  analytics: { nameMin: 2, nameMax: 40, maxParams: 25, keyMin: 2, keyMax: 40, valueMaxLen: 99 },
  boot: { fontTimeoutMs: 1500, restoreTimeoutMs: 1500, packTimeoutMs: 1500, platformRetryDelayMs: 1000, overlayTimeoutMs: 1500 },
  loading: { indicatorDelayMs: 300, failSafeMs: 25_000 },
  chunks: { retryDelaysMs: [500, 1500], timeoutMs: 8000 },
  worker: { callTimeoutMs: 10_000 },
  fish: { perWin: 3, hardBonus: 2, dailyBonus: 2, tutorial: 3, groupParticipation: 10, max: 999_999 },
  shop: { hintFish: 15, kittyFish: 30 },
  points: { perSize: 5, hardMultiplier: 2, flawless: 10, unaided: 10, daily: 15, event: 5, max: 2_000_000_000 },
  levelPoints: { perSize: 10, hardMultiplier: 2, streakStep: 10, streakCap: 10, modes: ['level', 'daily', 'event'], firstIncrement: 576, step: 96 },
  period: { kind: 'week', pointsPerFish: 1, modes: ['level', 'daily', 'event'], max: 99_999 },
  events: { teaseHours: 72, cardEndsSoonHours: 48 },
  rank: {
    fetchTimeoutMs: 3000,
    topCount: 10,
    fetchCount: 50,
    panelPopMs: 260,
    panelOutMs: 200,
    panelTapMinMs: 1200,
    tapPulseMs: 1400,
    submitMinIntervalMs: 10_000,
    minSolveMs: 3000,
    maxSolveMs: 86_400_000,
    dailyEpoch: '2026-01-01',
    periodEpoch: '2026-01-05',
    boards: { points: 'paw_points', daily: 'daily_fastest', eventPrefix: 'event_', period: 'period_points' },
    dailyBoard: false,
    overlayPlacement: 'fullscreen',
    showPanelWithoutProvider: true,
  },
  groups: {
    durationH: 72,
    rewardMode: 'participation',
    minWinsForReward: 3,
    rewardKitties: 2,
    rewardKittiesWithAd: 4,
    maxShown: 8,
    keep: 10,
    placeHints: 1,
  },
  iap: {
    readyTimeoutMs: 5000,
    catalogCacheMs: 600_000,
    tokensKept: 50,
    grantBeforeConsume: true,
    removeAdsMode: 'consume',
    products: [
      { id: 'remove_ads', noAds: true },
      { id: 'hints_15', hints: 15 },
      { id: 'kitties_8', kitties: 8 },
      { id: 'fish_250', fish: 250 },
      { id: 'fish_900', fish: 900 },
    ],
    catalog: [
      { id: 'remove_ads', noAds: true },
      { id: 'hints_15', hints: 15 },
      { id: 'kitties_8', kitties: 8 },
    ],
    // 250 fish ≈ 10 × 15 + 3 × 30 = 240; 900 fish = 30 × 15 + 15 × 30 (the old swap rates).
    retired: [
      { id: 'fish_250', hints: 10, kitties: 3 },
      { id: 'fish_900', hints: 30, kitties: 15 },
    ],
  },
  i18n: {
    locales: ['en', 'es', 'pt-BR', 'fr', 'de', 'it', 'id', 'tr', 'pl', 'ru', 'vi', 'th', 'ja', 'ko', 'zh-Hans', 'hi', 'ar'],
    fallback: 'en',
    rtl: ['ar'],
    localeTimeoutMs: 1200,
    releaseLocales: ['en'],
  },
  support: { feedbackUrl: '', feedbackOnFbig: false },
  settingsDot: { version: 1 },
});

/** Drag threshold for a cell of `cellPx` CSS px: max(8, 0.2 × cellPx) (02 §3 input.dragStartPx). */
export function dragStartPx(cellPx: number, c: GameConfig = cfg): number {
  return Math.max(c.input.dragStartMinPx, c.input.dragStartCellFraction * cellPx);
}

/** Recursive partial, for config variants in tests. */
export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends readonly unknown[] ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};

/** Returns a new frozen config with `patch` deep-merged over `base` (arrays are replaced). */
export function mergeConfig(patch: DeepPartial<GameConfig>, base: GameConfig = cfg): GameConfig {
  return deepFreeze(mergeDeep(base, patch) as GameConfig);
}

function mergeDeep(base: unknown, patch: unknown): unknown {
  if (patch === undefined) return base;
  if (!isPlainObject(base) || !isPlainObject(patch)) return patch;
  const out: Record<string, unknown> = { ...base };
  for (const [k, v] of Object.entries(patch)) out[k] = mergeDeep(base[k], v);
  return out;
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function deepFreeze<T>(o: T): T {
  if (typeof o === 'object' && o !== null && !Object.isFrozen(o)) {
    Object.freeze(o);
    for (const v of Object.values(o)) deepFreeze(v);
  }
  return o;
}
